### ISSUE TITLE
Shiny主题选择

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/XenaShiny#1]
为了节省大家的时间，我刚仔细看了下相关的主题，有5个比较适合。

- https://rstudio.github.io/shinythemes
- https://github.com/Appsilon/semantic.dashboard
- https://rinterface.com/shiny/shinydashboardPlus
- https://rinterface.com/shiny/bs4Dash/classic/
- https://rinterface.com/shiny/argonDash

大家有空看的适合不放投个票，说说自己想法啥的。

**Comment by fei0810** [comment]
倒数第二个404了，感觉最后一个好挺好看的 😄

**Comment by ShixiangWang** [comment]
@fei0810  有时候能显示出来
![image](https://user-images.githubusercontent.com/25057508/54655933-ad3b3d00-4afe-11e9-9afd-683b6d94ddca.png)
