### ISSUE TITLE
转录组分析

### ISSUE THREAD

**Issue by yinlisssss** [openbiox/XenaShiny#18]
### **目的**：
实现xena的转录组数据的下游分析
#### **2**. 下游分析包括：
a. 主页绘制某个基因的pancer表达情况，类似这样gepia那种风格（http://gepia.cancer-pku.cn/detail.php）
![image](https://user-images.githubusercontent.com/38618580/56120549-e69d8600-5fa0-11e9-8c44-29aedd7d2767.png)
b. 考虑到xena的数据都是normalized过的，就直接用了？第二页就分析PCA, 差异分析，同时绘制出火山图和热图。以及感兴趣基因的功能富集分析。
c. 根据临床数据，绘制基因的相关临床相关的箱图
d. 生存分析
e. 一些转录组的相关分析，比如gsea,gsva等等。
目前我能想到的就是这些了，看大家有什么想法没有。

**Comment by ShixiangWang** [comment]
我整理一下你的想法，相当于开发以下的modules：

- 数据导入
- 基因表达多个数据集的查看
- PCA
- 差异分析
- 热图
- 临床相关箱图
- GSEA
- GSVA

以上面modules的组合，可以单独做一个Pipeline页面

因为Xena的数据繁多，没有GEPIA使用的那么规则，所以前2个模块的数据的清理大家可能需要下点苦功夫。后面模块的开发可以使用一些示例数据，写成函数，然后提供相应的UI接口就可以了。

数据导入我的想法是支持3种模式

1. 直接使用API获取Xena的数据 （适用于针对性数据的获取，比如某个基因的Pancan表达）
2. 用户导入标准格式的数据，什么是标准需要我们指定和说明，当然，尽量与Xena保持一致，这样用户可以导入Xena数据，也可以分析自定义数据
3. 由顾恺目前负责开发的Repository直接导入（用户选定数据集后可以选择下载或是直接导入分析），也就是XenaShiny直接下载后导入R，不需要用户通过模式2导入

大家有空发表下自己的看法~

***

PS. 如果大家有看到别人已经实现了类似的功能，只要不侵权，都可以拿过来参考。

**Comment by longfei8533** [comment]
https://www.omicsolution.org/wu-kong-beta-linux/main/
这个网站虽然简陋，但里边有很多分析的模块可供参考，我们可以做的更好

**Comment by Byronxy** [comment]
转录组目前比较熟悉了。数据可视化部分可以来试着开发一下。
