### ISSUE TITLE
Pancan 数据提取与可视化一些问题

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/XenaShiny#29]
我发现目前这个有不少问题。
@Byronxy 先按照你的思路解决先关 checks的问题

1. 首先我需要你把 vis_toil_TvsN 的数据获取和可视化分开，或者通过条件判断支持一个直接可视化预先获取的数据集。因为我们主要是在 shiny中可视化，如果用户修改一次就调用一次从数据库获取数据的函数这不是一个好的选择。

2. 我发现你增加了一个数据集，这个要在 https://github.com/openbiox/XenaShiny/blob/master/R/data.R 中进行注释。另外我不知道这个数据集怎么得到的，是否可靠，一定要写清楚。如果能重复数据的来源，请把代码放入 https://github.com/openbiox/XenaShiny/tree/master/data-raw
![image](https://user-images.githubusercontent.com/25057508/60394462-54e0f600-9b57-11e9-8a04-77fb046eb9e0.png)

3. https://github.com/openbiox/XenaShiny/blob/master/R/GeomSplitViolin.R 这个里面好像主要是提供一个几何函数，我发现你都使用了 export，这个一定要注释所有的函数参数

![image](https://user-images.githubusercontent.com/25057508/60394472-6a562000-9b57-11e9-870d-02913d497d97.png)

4. 另外有个ggplot2的问题，我没太搞懂为什么要抛出一个NOTE，你检查下具体怎么修改
![image](https://user-images.githubusercontent.com/25057508/60394486-be610480-9b57-11e9-8998-a4192837b490.png)

等这些问题修正后我根据情况将我之前写的几个 数据操作和可视化函数 修改或者删除。

大家都可以探究下这个问题和可视化方案。

Shiny端相应的界面也需要开发，谁有兴趣呢？

我的想法是用户确定基因选择，然后生成图形后可以调整坐标，颜色等等。确定基因选择后获取数据会比较耗时，所以和后面的尽量间隔开。

***

在开发过程中，我发现需要频繁调用云端数据。有没有办法将数据cache到本地，如果利用的还是同样的数据，我们就不再从远程数据库请求？当shiny关闭后，将cache的数据删除掉？

**Comment by Byronxy** [comment]
好的，这个之后我慢慢修改

**Comment by ShixiangWang** [comment]
我在调试检查数据是否存在问题时发现 @Byronxy 你新建的数据集 同一样样本会对应不同的组织，这样正常吗？

下面是直接 UCSC获取的数据
![image](https://user-images.githubusercontent.com/25057508/60394871-3f6eca80-9b5d-11e9-9f76-59de36874904.png)

下面是你的新建的数据集中的显示
![image](https://user-images.githubusercontent.com/25057508/60394880-6fb66900-9b5d-11e9-8e54-cdfedb7d5325.png)

这样 同一个样本的表达值可能映射多次

![image](https://user-images.githubusercontent.com/25057508/60394894-9d9bad80-9b5d-11e9-9755-cfd227d67fc6.png)

请务必研究下你数据集以及不同type的可靠性。

**Comment by ShixiangWang** [comment]
@Byronxy 目前还剩第一个问题。要是有空的话，你可以整个UI输出这个功能结果。我当前写的太粗暴了。
