### ISSUE TITLE
2019-07月度开发任务

### ISSUE THREAD

**Issue by kaigu1990** [openbiox/XenaShiny#30]
由于个人原因在之前2个月内与大家进度脱节了，因此先看了下UCSCXenaShiny的development版本，按照现有的思路大致还需要完成的工作内容有5个modules和1个pipeline

**有些部分可能大家已经完成了，可以先在这个issues里反馈下**，然后大家可以相互提点建议完善下

我先按照分析顺序从头先挑2个modules作为本月中旬到8月中旬开发任务，如下：
*  Import&Export
* Data Tidy

首先我觉得Import&Export模块是用户使用的第一步，这样可以将分析模块和之前我们已经完成的数据搜索及下载模块有效的衔接在一起（不需要每次分析前必须load下数据）；这样的话，用户在下载数据后，可以先关闭shiny app，过段时间后再打开shiny app进行下一步分析

接着是Data Tidy模块，这个可方便用户对于数据做一些简单的过滤以及整理，主要是用于减少数据量，方便可视化分析；但是对于不同的数据来源，其数据结构可能不太一致，所以这个模块要么设计的通用性较好点，要么设计的详细点

以上是个人对于这两个模块的想法，欢迎大家补充讨论下

然后是需要先讨论下两个modules的UI界面设计，需要添加哪些UI功能，大家留言一起讨论呗

**Comment by ShixiangWang** [comment]
数据导入 支持

* 选择后导入
* 文件/目录导入
待补充

我们能不能在这个页面给出一个选择框，然后用户选择后然后再弹出接下来的操作，比如选第一个，我们就自动跳转到repository页面，选择第二个就弹出选择框让用户传入文件或者文件夹？

**Comment by kaigu1990** [comment]
1. 选择框是可以实现的，只是page页面跳转可能需要想想怎么实现，一般需要用到JS吧
2. 另外我觉得其实在repository页面load数据时，其操作是先下载数据到本地临时目录下，然后再读入R
那么我们其实可以通过一个UI将临时目录下的数据显示出来让用户选择，因为如果用户在repository页面选择了多个数据集，在后续可视化及分析时候还是必须先选择其中某个的
所以大家觉得通过一个UI去读取临时目录下的数据集文件并显示，然后用户勾选来指定其中某个
（但是这里有个问题是临时文件会变化的。。）
3. 或者还有其他方法

**Comment by ShixiangWang** [comment]
这第二点可以控制的，我们在临时目录下自定义一个数据XenaShiny的目录专门用来存储数据就可以。一般临时目录只会在关机后才会被清除，所以够用了。

**Comment by ShixiangWang** [comment]
这样，咱们周末全部人员抽出一到两小时，@kaigu1990 你主持一起讨论下目前这一轮具体怎么做和做哪些，然后接下来半个月一起相互帮助尽力实现。

@all 怎么样？

**Comment by kaigu1990** [comment]
本阶段的开发任务讨论内容如下：
1. 以RNA-seq数据作为最开始的模块测试数据，甲基化数据则@李胤(yliiiiiii) 来提供技术支持，如有其他数据可后续补充
2. 分析模块大致分为差异分析、相关性分析、聚类分析、富集分析、生存分析；每个人不分具体任务，大家发散想法吧~写好后可截个图发上来，大家讨论下哪个合适
3. 分析模块现阶段不必做的太细致，有大致样子即可；先集成到总的app.R代码中看看性能（例子在https://github.com/openbiox/XenaShiny/tree/master/inst/modules_apps）
4. 如果大家有已完成的分析模块页面，可在每周末两天发上来大家一起学习讨论下，最终合适的话就发布到github上方便大家测试下
5. 大家有已完成的代码也可发布上来，如有问题或者需要补充的内容可相互联系，一起开发

**Comment by longfei8533** [comment]
这两天在做生存分析的一个模块，Data Tidy 这个公共的模块我就先跳过了，其他很多都需要依赖这个

**Comment by ShixiangWang** [comment]
刚看到 https://github.com/ctlab/phantasus 这个，可以作为参考~

**Comment by ShixiangWang** [comment]
我刚提交了一个 合并，基于以下一些参考资料，大家有兴趣可以阅读

* https://shiny.rstudio.com/articles/scoping.html
* https://shiny.rstudio.com/articles/modules.html
* https://dreamrs.github.io/shinyWidgets/

**Comment by ShixiangWang** [comment]
根据之前我和熊逸做的事情把 基因表达的泛癌展示 Shiny 做好了。

![image](https://user-images.githubusercontent.com/25057508/62935334-6e818880-bdf9-11e9-9c5a-592fe676b678.png)


另外将其添加到了 Modules 的可视化页面中。

欢迎大家进行优化。然后@熊逸  有空可以增加更多的选项，比如选择不同癌症类型（类型太多有时候可能不是用户想要的，然后显示也不是特别美观），下载图片等
