### ISSUE TITLE
App won't start, "no file found" error

### ISSUE THREAD

**Issue by mdozmorov** [openbiox/XenaShiny#32]
Hi,

After a fresh install, `remotes::install_github("openbiox/XenaShiny")`, attempt to `app_run()` fails with error:

````
Error in system.file("inst", "shinyapp", "modules", package = "UCSCXenaShiny",  : 
  no file found
````

R version is 3.6.1, all latest updates included. What may be wrong?

Thanks,
Mikhail

**Comment by ShixiangWang** [comment]
@mdozmorov Thanks for reporting this issue. I have updated the code and you can pull the fixed version from github by remotes package.

Best,
Shixiang

**Comment by mdozmorov** [comment]
Thank you, @ShixiangWang, all works now.
