### ISSUE TITLE
XenaShiny 项目讨论会 - 2019-11-30

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/XenaShiny#53]
## 工作流

-   模块（特性）分支创建（从devel分支创建新的分支）

-   模块增加与测试

    -   主要利用 `golem::add_module( name = "my_first_module" )`新增模块模板，并进行开发
    -   其他可能有用的函数见 https://github.com/openbiox/XenaShiny/blob/devel/dev/02_dev.R
    -   测试运行 https://github.com/openbiox/XenaShiny/blob/devel/dev/run_dev.R 这个脚本

    有用的备忘表：https://thinkr.fr/golem_cheatsheet_v0.1.pdf

-   代码审查（合并到devel分支）

具体再看看：https://github.com/openbiox/XenaShiny/issues/47

## 功能及实现模块的选择

目标用户：

-   癌症（肿瘤）研究者
-   生信分析人员

功能与模块：

-   整个数据库数据集展示与选择
-   某队列数据临床数据的特征分布展示
-   数据集下载
-   独立的模块展示 UI
-   单基因表达数据的展示
-   基因表达生存分析

## 任务分配

-   整个数据库数据集展示与选择 - 顾恺
-   某队列数据临床数据的特征分布展示 - 赵飞
-   数据集下载 - 王诗翔
-   独立的模块展示 UI - 李胤
-   单基因表达数据的展示 - 熊逸
-   基因表达生存分析 - 赵龙飞

## 学习参考项目

-   http://gepia.cancer-pku.cn/index.html
-   http://www.bioinfo-zs.com/tiiat/
- https://github.com/likelet/IDEA
- https://github.com/GuoBioinfoLab/GSCALite

### 云平台

https://rstudio.cloud/project/714304

**Comment by ShixiangWang** [comment]
@kaigu1990 我有一个新的想法，能否不用表格（或者作为补充），以目录树的形式分级展示全部数据集 https://xenabrowser.net/datapages/ ，并支持搜索和过滤联动？并且条目支持点击？

**Comment by ShixiangWang** [comment]
@fei0810 http://www.cbioportal.org/study/summary?id=chol_msk_2018 这个作为参考哈

**Comment by kaigu1990** [comment]
@ShixiangWang 我觉得http://www.cbioportal.org/思路可以，之前用得时候还真没留意~现在看到确实可以借鉴下了

**Comment by fei0810** [comment]
> @fei0810 http://www.cbioportal.org/study/summary?id=chol_msk_2018 这个作为参考哈

好的，这个看起来还有点晕。
