### ISSUE TITLE
第一阶段开发任务

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/XenaShiny#8]
## 目的

开发基本的Home页面以及Repository页面。

开发使用Shiny模板shinythemes <https://rstudio.github.io/shinythemes/>

绘图使用echarts4r <https://echarts4r.john-coene.com/articles/get_started.html>

### Home页面

介绍Xena Shiny并给出汇总信息，类似于GDC（https://portal.gdc.cancer.gov/）或TCIA（https://tcia.at/home）。一开始不用好看，主要是能整出个大致的框架：

- 标题
- 简短介绍
- 信息图展示
- 资源展示（图标+数字）

![image](https://user-images.githubusercontent.com/25057508/54911072-96468180-4f28-11e9-80a7-9e61f60fc688.png)

![image](https://user-images.githubusercontent.com/25057508/54911281-166ce700-4f29-11e9-8b9d-841c3ae6a1a8.png)

### Repository页面

提供数据集的搜索、选择、下载功能。

页面左侧提供一些选择框

![image](https://user-images.githubusercontent.com/25057508/54911375-503ded80-4f29-11e9-855b-9c01f6d03ce4.png)

页面右侧提供用户过滤选择后数据集表格，默认可以展示所有信息（类似<https://portal.gdc.cancer.gov/repository>），表格需要支持链接，以便于后续开发。

## 任务领取

一开始可以自己构造数据实现原型。仓库Shiny已经写好了如何导入Xena数据集信息。

![image](https://user-images.githubusercontent.com/25057508/54912572-d65b3380-4f2b-11e9-86fc-d39f99e79205.png)

下面是5个任务。

- [x] 目前页面框架搭建 

整个类似下面的。左上方显示XenaShiny，然后包含3个页面，标签为Home、Repository和Developers

![image](https://user-images.githubusercontent.com/25057508/55046371-50023700-507c-11e9-89c0-311a60eb7d36.png)
 

- [ ] Home页面标题描述文字与资源标签数字显示

类似

![image](https://user-images.githubusercontent.com/25057508/54912128-ea526580-4f2a-11e9-9297-44a72b8839e4.png)

- [ ] 信息图

发挥自己的创造力，类似（我说的是形式类似，并不是具体的数据实现要一样）

![image](https://user-images.githubusercontent.com/25057508/54912202-1b329a80-4f2b-11e9-81bf-d20681e98cad.png)

![image](https://user-images.githubusercontent.com/25057508/54912286-4b7a3900-4f2b-11e9-8a3c-250cc7d0335a.png)

- [ ] 数据集过滤器

![image](https://user-images.githubusercontent.com/25057508/54912370-75336000-4f2b-11e9-992b-9a3347c3531a.png)

- [ ] 支持链接的表格显示

![image](https://user-images.githubusercontent.com/25057508/54912466-a57afe80-4f2b-11e9-8ce0-1a9d56a3af2a.png)

我最近花时间仔细研究下如何获取更多的Xena信息和底层代码，以及根据情况参与以上4项任务中。

加油！

**Comment by fei0810** [comment]
@ShixiangWang 我这两天用argonDash 写写我现在在做的网页，踩踩坑。

**Comment by ShixiangWang** [comment]
@fei0810 不用使用argon了，大家多票支持Shinythemes~
