### ISSUE TITLE
主题投票

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/XenaShiny#9]
选择暂时用于开发的主题。

- [ ] [argonDash](https://github.com/RinteRface/argonDash)，支持它回复1
- [x] [shinythemes](https://github.com/rstudio/shinythemes)，支持它回复2

**Comment by Byronxy** [comment]
2

**Comment by longfei8533** [comment]
喜欢原配

**Comment by longfei8533** [comment]
2

**Comment by ShixiangWang** [comment]
2 shinythemes以3票取胜。
